[project]
name = "jovimetrix"
description = "Integrates Webcam, MIDI, Spout and GLSL shader support. Animation via tick. Parameter manipulation with wave generator. Math operations with Unary and Binary support. Value conversion for all major types (int, string, list, dict, Image, Mask). Shape mask generation, image stacking and channel ops, batch splitting, merging and randomizing, load images and video from anywhere, dynamic bus routing with a single node, export support for GIPHY, save output anywhere! flatten, crop, transform; check colorblindness, make stereogram or stereoscopic images, or liner interpolate values and more."
version = "1.2.46"
license = { file = "LICENSE" }
dependencies = [
    "aenum>=3.1.15,<4",
    "aiohttp>=3.10.5",
    "blendmodes>=2024.1.1",
    "daltonlens>=0.1.5",
    "glfw>=2.7.0",
    "loguru>=0.7.2",
    "markdown>=3.7",
    "matplotlib>=3.8.4",
    "mido[ports-rtmidi]>=1.3.2",
    "mss>=9.0.1",
    "numba>=0.60.0",
    "numpy>=1.26.4",
    "opencv-contrib-python>=4.10.0.84",
    "Pillow>=10.4.0",
    "PyOpenGL>=3.1.7",
    "PyOpenGL-accelerate>=3.1.7; platform_machine=='x86_64'",
    "pywin32>=306; platform_system==\"Windows\"",
    "requests>=2.32.3",
    "scikit-image>=0.24.0",
    "scikit-learn>=1.5.1",
    "SpoutGL>=0.0.6; platform_system==\"Windows\"",
    "stereoscopy[auto_align]>=2.0.1",
    "vnoise>=0.1.0",
    "pyobjc-framework-Quartz>=7.3; platform_system=='Darwin'"
]

[project.urls]
Repository = "https://github.com/Amorano/Jovimetrix"

[tool.comfy]
PublisherId = "amorano"
DisplayName = "Jovimetrix"
Icon = "https://raw.githubusercontent.com/Amorano/Jovimetrix-examples/master/res/logo-jovimetrix.png"
